name: PR Style Check

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read

jobs:
  description:
    name: Description
    runs-on: ubuntu-latest
    env:
      # Do not use ${{ github.event.pull_request.body }} directly in run command.
      BODY: ${{ github.event.pull_request.body }}
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Check comment out lines
        run: |
          if [[ $BODY =~ "<!--" ]]; then
              echo "PR description contains '<!--'. Please remove all the comment out lines in the template after carefully reading them."
              exit 1
          fi
          if [[ $BODY =~ "-->" ]]; then
              echo "PR description contains '-->'. Please remove all the comment out lines in the template after carefully reading them."
              exit 1
          fi
      - name: Check the first line matches '**Description**'
        run: |
          first_line=$(echo -n "$BODY" | head -n 1)
          trimmed_first_line=$(echo "$first_line" | sed 's/[[:space:]]*$//')
          echo "$trimmed_first_line='$trimmed_first_line'"
          if [[ "$trimmed_first_line" != "**Description**" ]]; then
            echo "The first line of the PR description must be '**Description**'"
            exit 1
          fi
      - name: Check no markdown format link in PR description.
        run: |
          if echo "$BODY" | grep -q '\[[^]]\+\](\([^)]\+\))'; then
            echo "PR description contains markdown format link. Please remove all of them."
            echo "If you want to refer to a link, please use the following format where you place the link at the end of the PR description:"
            echo ""
            echo "**Description**:"
            echo "This modifies foo bar. The official documentation can be found at [1] and [2]. Please refer to them for more details."
            echo ""
            echo "1: https://example.com"
            echo "2: https://another.com"
            exit 1
          fi

  title:
    name: Title
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            docs
            style
            feat
            test
            build
            ci
            chore
            revert
            release
            api
            deps
            e2e
            extproc
            controller
            translator
            examples
            blog
            site
            backport
            cli
            refactor
            mcp
            aigw
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
